### ISSUE TITLE
Support AWS per-region hosts

### ISSUE THREAD

**Issue by pimterry** [APIs-guru/aws2openapi#14]
The current code always outputs `<endpointprefix>.amazonaws.com` as the host for every spec. That is often (but not always) one correct host, but there's typically many other valid hosts, usually one for each AWS region.

This results in specs that a) don't represent all valid hosts, and b) sometimes don't represent _any_ valid hosts, e.g. the SQS spec uses [sqs.amazonaws.com](https://github.com/APIs-guru/openapi-directory/blob/master/APIs/amazonaws.com/sqs/2012-11-05/swagger.yaml#L36), which doesn't even have a DNS record. SQS requests should instead be sent to `sqs.<region-name>.amazonaws.com` e.g. `sqs.us-east-1.amazonaws.com` (see https://docs.aws.amazon.com/general/latest/gr/rande.html#sqs_region).

Imo, it would be better if the specs included the valid host URLs. Fortunately the logic to work out all the valid hosts isn't too bad, the rules are documented at https://github.com/aws/aws-sdk-js/blob/master/lib/region_config_data.json, with associated logic at https://github.com/aws/aws-sdk-js/blob/master/lib/region_config.js.

The hard part is how to output this. I'm happy to put together a PR for this, but OpenAPI v2 only allows a single host, so this isn't representable. I can see a couple of sensible options:

* Convert to OpenAPI v3 first, then use OpenAPI v3's [templated `servers`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#serverObject) field
* Add a custom field emulating this temporarily for v2, e.g. `x-v3-servers`, which exactly matches the format for v3, so tools that are aware of it can use it whilst others use the existing `host` field. Swagger2openapi can then just rename it when converting to v3.

I've got some time to put together a PR for this, but not really to convert all this logic to v3 beforehand. Any chance you do? Otherwise, what do you think we should do?

**Comment by MikeRalphson** [comment]
Hi - thanks for bringing this up and detailing everything.

I've just started a new role, so time is tight at the moment for open-source work.

So, as you say, we can:

* stack this behind the planned work to produce the output natively in OAS 3.0
* use a specification extension

`swagger2openapi` already supports a convention of using `x-servers`, as documented [here](https://github.com/Mermade/swaggerplusplus#swaggerplusplus) which is picked up by the conversion process, and this is also used by a small number of tools including ReDoc.

To address your comment from another issue, you noted that this converter works with the input document in-place, mutating it as it goes. This has one specific benefit, that the output document will fail validation if Amazon add anything which we're not expecting to their document format, as we won't know to remove it. This may not be the case if we only visit parts of the input document we know about.

I did experiment with inferring a schema for the input documents, which could alert us to changes, but so far that was only done as a one-off exercise when writing the original converter.

If this causes any specific problems, we can always use a hybrid approach (i.e. completely rebuilding shape/schema objects from scratch if necessary).

As to which approach we should take, I'm easy, so it may depend on when you have time for a PR and how much time you have available.

**Comment by pimterry** [comment]
Sure, that's really useful. For now I'll put together a PR to start using `x-servers` sometime this week. Given that we've already got conversion in place, that works perfectly for me.

No worries about your time, I know maintaining things can be tricky when you get busy! Sorry I keep finding more things to do, I'll try and keep it all quick & easy.
