### ISSUE TITLE
The info.contact.x-twitter field causes openapi-generator to fail

### ISSUE THREAD

**Issue by sverch** [APIs-guru/aws2openapi#27]
I'm trying to use the aws specs generated by this project in https://github.com/OpenAPITools/openapi-generator/, but I hit this error:

```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 165
Errors: 
	-attribute info.contact.x-twitter is unexpected
Warnings: 
	-attribute info.contact.x-twitter is unexpected

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:424)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:453)
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:407)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:60)
```

Here's the script I'm using to run the generator:

```bash
#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail

NUM_ARGS_REQUIRED=1
if [ $# -ne "${NUM_ARGS_REQUIRED}" ]; then
    cat <<EOF
Usage: $0 <openapi-directory>

    Try to generate IAM from openapi directory.

EOF
    exit 1
fi

run () {
    echo "+" "$@" 1>&2
    "$@"
}

OPENAPI_DIRECTORY=$1

pushd "${OPENAPI_DIRECTORY}/APIs/amazonaws.com/iam/2010-05-08"
docker run --rm -v "${PWD}:/local/out/rust/" openapitools/openapi-generator-cli generate \
    -i /local/out/rust/swagger.yaml \
    -g rust \
    -o /local/out/rust/generated \
    --additional-properties packageName=aws_iam_client --library=reqwest
popd
```

**Comment by MikeRalphson** [comment]
Have you reported this on the openapi-generator repo? This specification extension is definitely valid.

**Comment by sverch** [comment]
I haven't actually.  I tried to look for the spec, and I found [this](https://github.com/APIs-guru/openapi-directory/wiki/specification-extensions).  It looks like that's an extension specific to this vendor, and the openapi-generator does not support it.  Should the openapi generator be ignoring extensions?

Thanks for making this by the way!

**Comment by MikeRalphson** [comment]
Yes, openapi-generator should ignore all specification extensions (where allowed) that it does not understand.

**Comment by MikeRalphson** [comment]
Related to https://github.com/swagger-api/swagger-parser/issues/1204

**Comment by MikeRalphson** [comment]
Closing as it's not an issue with this repo.

**Comment by sverch** [comment]
Well, I was going to finally file an issue on the openapi generator, but parsing the same spec now works for me, so they likely fixed it already.

I also see you updated the openapi directory to [openapi 3.0](https://github.com/APIs-guru/openapi-directory/commit/830426e34b85c7a47246a96e5827300973ae80da).  I was working through some other errors with the generator, but with that update those are now resolved as well.  Thanks!

**Comment by MikeRalphson** [comment]
Excellent, thanks for the feedback.
