### ISSUE TITLE
S3 API's error not handled correctly

### ISSUE THREAD

**Issue by Xuanwo** [APIs-guru/aws2openapi#40]
```
    BucketAlreadyExists: {}
    BucketAlreadyOwnedByYou: {}
```

May be we need to fill the error type or just ignore them.

**Comment by MikeRalphson** [comment]
Again, as per #39 this is a limitation of the source description file. It does not include any definition for the `Shape`s "BucketAlreadyExists" or "BucketAlreadyOwnedByYou".

Perhaps no schema is returned with these errors, and so the empty schema (`{}`) would be correct anyway?
